Django_2_blog/urls.py
from django.urls import path, include
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap

sitemaps = {
    'posts': PostSitemap,
}

urlpatterns = [
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap'),
]

blog/urls.py
from django.urls import path
from . import views
from .feeds import LatestPostsFeed

app_name = 'blog'

urlpatterns = [
    # Widoki posta (jest 'path' i 're_path')
    path('', views.post_list, name='post_list'),
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    # path('', views.PostListView.as_view(), name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/',
         views.post_detail,
         name='post_detail'),
    path('<int:post_id>/share/',
         views.post_share, name='post_share'),
    path('feed/', LatestPostsFeed(), name='post_feed'),
    path('search/', views.post_search, name='post_search')
]

blog/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth.models import User
from taggit.managers import TaggableManager


# Create your models here.
class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(status='published')


class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250,
                            unique_for_date='publish')
    author = models.ForeignKey(User,
                               on_delete=models.CASCADE,
                               related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10,
                              choices=STATUS_CHOICES,
                              default='draft')
    tags = TaggableManager()

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    objects = models.Manager()  # Menedżer domyślny
    published = PublishedManager()  # Menedżer niestandardowy

    def get_absolute_url(self):
        return reverse('blog:post_detail',
                       args=[
                           self.publish.year,
                           self.publish.strftime('%m'),
                           self.publish.strftime('%d'),
                           self.slug
                       ]
                       )


class Comment(models.Model):
    post = models.ForeignKey(Post,
                             on_delete=models.CASCADE,
                             # related_name='comments'
                             )
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return f'Comment added by {self.name} for post {self.post}'

blog/forms.py
from django import forms
from .models import Comment


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False,
                               widget=forms.Textarea)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')


class SearchForm(forms.Form):
    query = forms.CharField()

blog/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView
from django.db.models import Count
from django.contrib.postgres.search import SearchVector, SearchQuery, \
    SearchRank, TrigramSimilarity
from .forms import EmailPostForm, CommentForm, SearchForm
from .models import Post, Comment
from django.core.mail import send_mail
from taggit.models import Tag


# from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


# Create your views here.
class PostListView(ListView):
    queryset = Post.published.all()
    context_object_name = 'posts'
    paginate_by = 3
    template_name = 'blog/post/list.html'


def post_list(request, tag_slug=None):
    # pobranie wszystkich postów gdzie status='published'
    object_list = Post.published.all()
    tag = None

    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])
    paginator = Paginator(object_list, 3)  # 3 posts on each page
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        # if variable page bigger than max page number
        posts = paginator.page(paginator.num_pages)
    return render(request, 'blog/post/list.html', {'page': page,
                                                   'posts': posts,
                                                   'tag': tag})


def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post,
                             slug=post,
                             status='published',
                             publish__year=year,
                             publish__month=month,
                             publish__day=day)
    comment_created = False
    # List of active comments for a given post
    comments = post.comment_set.filter(active=True)

    if request.method == 'POST':
        # Comment has been published
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            # Utworzenie obiektu Comment, ale jeszcze
            # nie zapisuję go w bazie danych
            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            new_comment.save()
            comment_created = True
    else:
        comment_form = CommentForm()

    # Similar posts list
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids) \
        .exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')) \
                        .order_by('-same_tags', '-publish')[:4]

    return render(request, 'blog/post/detail.html',
                  {'post': post,
                   'comments': comments,
                   'comment_form': comment_form,
                   'comment_created': comment_created,
                   'similar_posts': similar_posts,
                   })


def post_share(request, post_id):
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False

    if request.method == 'POST':
        form = EmailPostForm(request.POST)
        if form.is_valid():
            # Słownik z polami formularza i ich wartości
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = f'{cd["name"]} ({cd["email"]}) encourages you ' \
                      f'to read {post.title}.'
            message = f'Read post "{post.title}" on {post_url}' \
                      f'\n\n Comment added by {cd["name"]}: {cd["comments"]}'
            send_mail(subject, message, 'admin@myblog.com', [cd['to']])
            sent = True
    else:
        # print(form.errors)
        form = EmailPostForm()
    return render(request, 'blog/post/share.html', {'post': post,
                                                    'form': form,
                                                    'sent': sent})


def post_search(request):
    form = SearchForm()
    query = None
    results = []
    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            search_vector = SearchVector('title', weight='A') + SearchVector(
                'body', weight='B')
            search_query = SearchQuery(query)
            # results = Post.published.annotate(
            #     # search=search_vector,
            #     rank=SearchRank(search_vector, search_query)
            # ).filter(rank__gte=0.3).order_by('-rank')
            search_query = SearchQuery(query)
            results = Post.published.annotate(
                similarity=TrigramSimilarity('title', query)
            ).filter(similarity__gte=0.1).order_by('-similarity')
    return render(request,
                  'blog/post/search.html',
                  {'form': form,
                   'query': query,
                   'results': results}
                  )

blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}
{%  load blog_tags %}

{% block title %}{{ post.title }}{% endblock %}

{% block content %}
<div class="testing">
{#    <br><h1>{{ post_tags_ids }}</h1>#}
{#    <h2>{{ post_tags_names }}</h2><br>#}
{#    <br><h1>{{ similar_posts }}</h1><br>#}
{#    {% for similar_post in similar_posts %}#}
{#        name: {{ similar_post }}<br>#}
{#        tags:#}
{#        {% for tag in similar_post.tags.all %}#}
{#            {{ tag.name }}#}
{#        {% endfor %}#}
{#        <br>#}
{#        similar tags no: {{ similar_post.same_tags }}#}
{#        {% if not forloop.last %}#}
{#            <br>#}
{#        {% endif %}#}
{#    {% endfor %}#}
</div>  <!-- functions check -->

    <h1>{{ post.title }}</h1>
    <p class="date">
    Published {{ post.publish }} by {{ post.author }}
    </p>
    {{ post.body|markdown }}
    {% include 'tags.html' with tags=tags %}
    <p>
        <a href="{% url "blog:post_share" post.id %}">
            Share post
        </a>
    </p>

    <h2>Similar posts</h2>
    {% for post in similar_posts %}
        <p>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
            {% include 'tags.html' with tags=tags %}
        </p>
    {% empty %}
        There are no similar posts.
    {% endfor %}

    {% with comments.count as total_comments  %}
        <h2>
            {{ total_comments }} comment{{ total_comments|pluralize:"s" }}
        </h2>
    {% endwith %}
    {% for comment in comments %}
        <div class="comment">
            <p class="info">
                Comment no {{ forloop.counter }} added by {{ comment.name }}
                {{ comment.created }}
            </p>
            {{ comment.body|linebreaks }}
        </div>
        {% empty %}
            <p>There are no comments yet.</p>
    {% endfor %}

    {% if comment_created %}
        <h2>Your comment has been added</h2>
    {% else %}
        <form action="." method="post">
            {{ comment_form.as_p }}
            {% csrf_token %}
            <p><input type="submit" value="Add a comment"></p>
        </form>
    {% endif %}

{% endblock %}

blog/templates/blog/post/latest_posts.html
<ul>
    {% for post in latest_posts %}
        <li>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </li>
    {% endfor %}
</ul>

blog/templates/blog/post/list.html
{% extends "blog/base.html" %}
{%  load blog_tags %}

{% block title %}My blog{% endblock %}

{% block content %}
    <h1>My blog</h1>

        {% if tag %}
            <h2>Tagged posts: {{ tag.name }} </h2>
        {% endif %}

        {% for post in posts %}
            <h2>
                <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
            </h2>
            {% include 'tags.html' with tags=tags %}
            <p class="date">
                Published {{ post.publish }} by {{ post.author }}
            </p>
            {{ post.body|markdown|truncatewords_html:30 }}
        {% endfor %}
    {% include "pagination.html" with page=posts %}
{% endblock %}

blog/templates/blog/post/search.html
{% extends "blog/base.html" %}

{% block title %}Search{% endblock %}

{% block content %}
    {% if "query" in request.GET %}
    <h1>Posts including "{{ form.cleaned_data.query }}"</h1>
    {% with results.count as total_results %}
        <h3>
            Found {{ total_results }} result{{ total_results|pluralize:"s" }}
        </h3>
    {% endwith %}
    {% for result in results %}
        {% with post=result %}
            <h4><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h4>
            {{ post.body|truncatewords:5 }}
        {% endwith %}
    {% empty %}
        <p>No results for given input</p>
    {% endfor %}
    <p><a href="{% url "blog:post_search" %}">Search again</a></p>
    {% else %}
        <h1>Search posts</h1>
        <form action="." method="get">
            {{ form.as_p }}
            <input type="submit" value="Search">
        </form>
    {% endif %}
{% endblock %}

blog/templates/blog/post/share.html
{% extends 'blog/base.html' %}

{% block title %} Share a post {% endblock %}

{% block content %}
    {% if sent %}
        <h1>The email has been sent</h1>
        <p>
            The email "{{ post.title }}" to {{ form.cleaned_data.to }} has been successfully sent
        </p>
    {% else %}
        <h1>Share "{{ post.title }} via e-mail</h1>
        <form action="." method="post">
            {{ form.as_p }}
            {% csrf_token %}
            <input type="submit" value="Send the email">
        </form>
    {% endif %}
{% endblock %}